"""Generate the files that mirror a Python source of truth.

    python -m codegen           # rewrite every generated file
    python -m codegen --check   # exit 1 and name the stale files; write nothing

Generated (never edit these by hand; edit the source and rerun):

  docs/schema/*.schema.json   <- mtjschema.py     (the .mtj manifest schemas)
  viewer/tokens.js            <- design_tokens.py (the viewer's palette)
  viewer/style.css  :root     <- design_tokens.py (between the BEGIN/END markers)
  .streamlit/config.toml      <- design_tokens.py (the explorer's theme)

`tests/test_codegen.py` runs the check, so CI fails on drift.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
NOTE = "generated by `python -m codegen` from {src}; do not edit by hand"
_CSS_BLOCK = re.compile(r"/\* BEGIN GENERATED[^*]*\*/\n.*?/\* END GENERATED \*/\n", re.S)


def _schemas() -> dict[Path, str]:
    import mtjschema

    return {ROOT / "docs" / "schema" / name: json.dumps(schema, indent=2) + "\n"
            for name, schema in mtjschema.schema_files().items()}


def _tokens_js() -> str:
    import design_tokens as T

    data = {"marbleColors": T.MARBLE_COLORS, "terrainColorscale": T.TERRAIN_COLORSCALE,
            "css": T.CSS_ROOT}
    return (f"// {NOTE.format(src='design_tokens.py')}\n"
            '"use strict";\n'
            f"const MOTTLED_TOKENS = Object.freeze({json.dumps(data, indent=2)});\n"
            'if (typeof module !== "undefined") module.exports = MOTTLED_TOKENS;\n')


def _css_block() -> str:
    import design_tokens as T

    body = "".join(f"  --{k}: {v};\n" for k, v in T.CSS_ROOT.items())
    return (f"/* BEGIN GENERATED: {NOTE.format(src='design_tokens.CSS_ROOT')} */\n"
            f":root {{\n{body}}}\n/* END GENERATED */\n")


def _style_css() -> str:
    path = ROOT / "viewer" / "style.css"
    css = path.read_text(encoding="utf-8")
    if _CSS_BLOCK.search(css):
        return _CSS_BLOCK.sub(lambda _: _css_block(), css, count=1)
    # first run: replace the hand-written :root block with the generated one
    return re.sub(r":root \{\n.*?\n\}\n", lambda _: _css_block(), css, count=1, flags=re.S)


def _streamlit_toml() -> str:
    import design_tokens as T

    lines = [f"# {NOTE.format(src='design_tokens.STREAMLIT_THEME')}", "[theme]"]
    lines += [f'{k} = "{v}"' for k, v in T.STREAMLIT_THEME.items()]
    return "\n".join(lines) + "\n"


def outputs() -> dict[Path, str]:
    """Every generated file and the content it should have."""
    return {**_schemas(),
            ROOT / "viewer" / "tokens.js": _tokens_js(),
            ROOT / "viewer" / "style.css": _style_css(),
            ROOT / ".streamlit" / "config.toml": _streamlit_toml()}


def stale() -> list[Path]:
    return [p for p, text in outputs().items()
            if not p.exists() or p.read_text(encoding="utf-8") != text]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="python -m codegen", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="report stale files and exit 1; write nothing")
    args = ap.parse_args(argv)
    if args.check:
        bad = stale()
        for p in bad:
            print(f"stale: {p.relative_to(ROOT)} (run `python -m codegen`)", file=sys.stderr)
        return 1 if bad else 0
    for p, text in outputs().items():
        if not p.exists() or p.read_text(encoding="utf-8") != text:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
