// generated by `python -m codegen` from design_tokens.py; do not edit by hand
"use strict";
const MOTTLED_TOKENS = Object.freeze({
  "marbleColors": [
    "#4B7CF3",
    "#00CCA8",
    "#D4934A",
    "#E05050",
    "#38B07A",
    "#8FA7F7",
    "#5CE0C6",
    "#E6B884",
    "#F08A8A",
    "#7FD0AC"
  ],
  "terrainColorscale": [
    [
      0.0,
      "#04060E"
    ],
    [
      0.22,
      "#0C1020"
    ],
    [
      0.45,
      "#1C2A55"
    ],
    [
      0.68,
      "#2F55B8"
    ],
    [
      0.86,
      "#4B7CF3"
    ],
    [
      1.0,
      "#C8D4FB"
    ]
  ],
  "css": {
    "color-base": "#080B18",
    "color-surface-0": "#0C1020",
    "color-surface-1": "#11162A",
    "color-panel": "rgba(12, 16, 32, 0.92)",
    "color-border": "#1E2540",
    "color-border-strong": "#283050",
    "color-fg-1": "#EDF0FA",
    "color-fg-2": "#818FB8",
    "color-accent": "#4B7CF3",
    "color-accent-subtle": "rgba(75, 124, 243, 0.08)",
    "color-loss": "#E05050",
    "color-amber": "#D4934A",
    "color-live": "#00CCA8",
    "radius-xs": "2px",
    "radius-sm": "3px",
    "ease-precision": "cubic-bezier(0.16, 1, 0.3, 1)"
  }
});
if (typeof module !== "undefined") module.exports = MOTTLED_TOKENS;
